### ISSUE TITLE
Not available on MELPA

### ISSUE THREAD

**Issue by g3ntleman** [purcell/ns-auto-titlebar#1]
Contrary to the readme, the package is not available on melpa.

**Comment by purcell** [comment]
Erm: https://melpa.org/#/ns-auto-titlebar

**Comment by purcell** [comment]
Also download link at the above address works fine and it's listed in https://melpa.org/packages/archive-contents.

**Comment by g3ntleman** [comment]
Rightfully closed. When I wrote this issue, mela site was not showing any results and the download within emacs failed as well. Maybe they had a general hiccup.

**Comment by purcell** [comment]
Ah, weird. I'm not aware that we had any downtime, but I guess it's possible.
